import SidebarLayout from '@/components/layout/sidebar-layout';
import { Sidebar } from '@/components/navigation/sidebar';
import { Preview } from '@/components/preview';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SidebarLayout sidebarContent={<Sidebar />} mainContent={<Preview />} />
    </>
  );
}
